### ISSUE TITLE
This package requires php ^7.1.3 <7.3.14 but your PHP version (7.3.14) does not satisfy that requirement.

### ISSUE THREAD

**Issue by Zt-freak** [loophp/phptree#17]
Please allow more recent PHP versions to use PHPtree.

## Steps required to reproduce the problem

1. run `composer require loophp/phptree`

## Expected Result

* phptree installs

## Actual Result

* version error
```Using version ^2.6 for loophp/phptree
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1.3 <7.3.14 but your PHP version (7.3.14) does not satisfy that requirement. ```

**Comment by drupol** [comment]
This package requires: `"php": ">= 7.1"`, see the composer.json :-)

**Comment by Zt-freak** [comment]
wow I'm big dumb my php version is `"php": "^7.1.3 <7.3.14"` I forgot a =

**Comment by Samvdg** [comment]
Im with @Zt-freak , while we got 1 step closer because of this, now i had to change PHP versions (i had 7.4) and when i finally did this, now  i'm missing SQL drivers for some reason. It's not important or related. Just thought i'd update you on what happened since.

**Comment by drupol** [comment]
Weird... 

I didn't do anything to composer.json since more than a year ago! See: https://github.com/loophp/phptree/blame/master/composer.json#L19

**Comment by Samvdg** [comment]
haha yeah i'm just doing dumb stuff most definitely, doesn't have anything to do with your project

**Comment by drupol** [comment]
Ah ok :-)
