### ISSUE TITLE
KeyValueNode is buggy

### ISSUE THREAD

**Issue by FrantzUml** [loophp/phptree#54]
I understand Key as the Id of the Node, so:
- the find method must compare keys
- the delete method must remove by key
- the add method must check if a Node with same key already exist

Proposal:
================================
- make children attribute of Node as protected
- modify function find in KeyValueNode to check key
- the add method keeps problematic as we should check all nodes of tree, decreasing performance

**Comment by drupol** [comment]
Thanks for your feedback!

I don't use PHP these last months, feel free to submit PR to fix this, it would be greatly appreciated.
