### ISSUE TITLE
The height of tree is invalid

### ISSUE THREAD

**Issue by FrantzUml** [loophp/phptree#55]
The algorithm used to calculate the height of tree is not correct.
The method calculate the max depth of a node N, but not the depth (+1) of the deepest node in the tree.

Two methods to calculate the real height:
- recursicve one
- iterative with using a queue structure

**Comment by drupol** [comment]
Thanks for your feedback!

Just like the other issue, I don't use PHP any more, feel free to submit PR to fix this, it would be greatly appreciated.
